"use client";
import { FeedbackProvider } from "@/state/feedback";
import "./globals.css";
import { Jost } from "next/font/google";
import { SortedFeedbackProvider } from "@/state/sortedFeedback";

const jost = Jost({ subsets: ["latin"], variable: "--font-jost" });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${jost.variable} font-jost`}
        suppressHydrationWarning={true}
      >
        <FeedbackProvider>
          <SortedFeedbackProvider>{children}</SortedFeedbackProvider>
        </FeedbackProvider>
      </body>
    </html>
  );
}
